#include "rtti.hpp"

DEFINE_FUNDAMENTAL(bool)

DEFINE_FUNDAMENTAL(signed char)
DEFINE_FUNDAMENTAL(unsigned char)
DEFINE_FUNDAMENTAL(char)
DEFINE_FUNDAMENTAL(wchar_t)
DEFINE_FUNDAMENTAL(char16_t)
DEFINE_FUNDAMENTAL(char32_t)
DEFINE_FUNDAMENTAL(char8_t)

DEFINE_FUNDAMENTAL(short int)
DEFINE_FUNDAMENTAL(unsigned short int)
DEFINE_FUNDAMENTAL(int)
DEFINE_FUNDAMENTAL(unsigned int)
DEFINE_FUNDAMENTAL(long int)
DEFINE_FUNDAMENTAL(unsigned long int)
DEFINE_FUNDAMENTAL(long long int)
DEFINE_FUNDAMENTAL(unsigned long long int)

DEFINE_FUNDAMENTAL(float)
DEFINE_FUNDAMENTAL(double)
DEFINE_FUNDAMENTAL(long double)